wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1652450128
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 35
      - 40
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 35
      - 40
      - 41
      - 49
      - 51
      - 53
      - 55
      4: 3.9.7
      5: 0.12.16
      6: 4.17.0
      8:
      - 2
      - 5
